{application,logic_visualizer,
             [{modules,['Elixir.LogicVisualizer','Elixir.LogicVisualizer.CLI',
                        'Elixir.LogicVisualizer.CLI.Main',
                        'Elixir.LogicVisualizer.Education',
                        'Elixir.LogicVisualizer.Examples',
                        'Elixir.LogicVisualizer.HOLIntegration.HOLConverter',
                        'Elixir.LogicVisualizer.Parser.ExpressionParser',
                        'Elixir.LogicVisualizer.Parser.Precedence',
                        'Elixir.LogicVisualizer.Processing.StepProcessor',
                        'Elixir.LogicVisualizer.Prover',
                        'Elixir.LogicVisualizer.Visualization.TreeVisualizer']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,runtime_tools,hol,
                             nimble_parsec,earmark]},
              {description,"A comprehensive Elixir project for parsing and visualizing logical expressions using HOL library"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
