{application,hol,
             [{modules,['Elixir.Benchmarking.Unification',
                        'Elixir.HOL.ChurchNumerals','Elixir.HOL.Data',
                        'Elixir.HOL.Data.Unification',
                        'Elixir.HOL.Substitution','Elixir.HOL.Terms',
                        'Elixir.HOL.Unification',
                        'Elixir.HOL.Unification.Bindings',
                        'Elixir.LoggerHelper','Elixir.PrettyPrint',
                        'Elixir.TPTPParser']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A higher order logic pre-unification implementation"},
              {registered,[]},
              {vsn,"1.0.1"}]}.
